In [2]:
import cv2
import numpy as np
import datetime
import os

In [3]:
cam =cv2.VideoCapture(0)

In [4]:
cam.set(3,640) #set width as 640
cam.set(4,480) #set height as 480
scale=3 #resize of the image
wP=210*scale #width of the papper
hP=297*scale #height of the papper

In [5]:
def save_frame(frame):
    now=datetime.datetime.now()
    filename = "frames/frame_{}.png".format(now.strftime("%Y-%m-%d_%H-%M-%S"))
    cv2.imwrite(filename, frame)

In [6]:
while True:
    check, frame = cam.read()#capture frame from video
    cv2.imshow('video', frame)
    key=cv2.waitKey(1)
    if key == ord('s'):
        save_frame(frame)
    if key==27 :
        break
cam.release()
cv2.destroyAllWindows()

In [18]:
#get images
path_to_image=("/home/agj/VSCODE/Jeffrin/Project obj-measur-sys/frames/")
def get_latest_image(directory, valid_extensions=('jpg', 'jpeg', 'png')):
    #get filepaths of all files and dirs in the given dir
    valid_files=[os.path.join(directory, filename) for filename in os.listdir(directory)]
    valid_files=[f for f in valid_files if '.' in f and f.rsplit('.',1)[1] in valid_extensions and os.path.isfile(f)]
    #f.rsplit('.',1)[1] split the string once and select the string after ".".
    #os.path.isfile(f) checks the string f corresponds to a valid file or not.
    if not valid_files:
        raise ValueError("No valid images in %s" % directory)
    return max(valid_files, key=os.path.getmtime)
last_image=get_latest_image(path_to_image)

In [19]:
#read image
imge=cv2.imread(last_image)
imge_cpy=imge.copy()

cv2.imshow('image', imge)
cv2.imshow('Img_cpy', imge_cpy)
cv2.waitKey(5000)
cv2.destroyAllWindows()

In [9]:
gray=cv2.cvtColor(imge, cv2.COLOR_BGR2GRAY)
cv2.imshow('gray', gray)
cv2.waitKey(5000)
cv2.destroyAllWindows()

In [10]:
blur=cv2.GaussianBlur(gray, (3,3), 0)
cv2.imshow("blur", blur)
cv2.waitKey(5000)
cv2.destroyAllWindows()

In [11]:
edges=cv2.Canny(gray, 250,100) #default sobelkernel=3
edge_cpy=cv2.Canny(blur, 180,210) #default sobelkernel=3
contours, _= cv2.findContours(edge_cpy, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
cv2.imshow("canny_gray", edges)
cv2.imshow("canny_1", edge_cpy)
cv2.waitKey(50000)
cv2.destroyAllWindows()
print(len(contours))

619


In [12]:
#removing small contours
_, thresh=cv2.threshold(edge_cpy, 127, 255, cv2.THRESH_BINARY)
# Loop through contours
for cnt in contours:
    if cv2.contourArea(cnt)< 5 :
        cv2.drawContours(thresh, [cnt], 0, 0, -1)
    

cv2.imshow('Out_put Image', thresh)
cv2.imshow("rec", imge)

cv2.waitKey(50000)
cv2.destroyAllWindows()

In [13]:
# Find the contour with the largest area, which is most likely to be the rectangle
max_area = 0
max_contour = None
for contour in contours:
    area = cv2.contourArea(contour)
    
    print(area)
    if area > max_area:
        max_area = area
        max_contour = contour

# Get the coordinates and dimensions of the rectangle bounding the contour
x, y, w, h = cv2.boundingRect(max_contour)
topleft_axes=(x,y)
bottomright_axes=(x+w,y+h)
width, height=w, h
w


0.0
0.0
0.5
0.5
3.0
1.0
6.0
0.0
2.5
13.5
0.0
0.0
6.5
1.5
0.0
1.0
0.0
12.5
8.0
20.0
10.5
1.0
11.0
18.0
2.5
6.5
10.5
15.0
1.0
74.0
59.5
14.0
21.5
11.0
8.0
18.5
3.5
4.0
3.5
2.5
5.5
46.0
1.0
28.5
1.5
0.0
0.5
13.0
28.0
3.5
13.0
12.0
0.0
7.5
60.5
0.0
136.5
1.0
4.5
7.0
0.0
2.0
124.0
0.5
0.0
0.5
3.0
54.5
76.0
4.0
1.0
0.0
0.0
42.0
83.0
16.5
1.5
54.5
24.0
3.5
22.0
7.0
48.5
104.5
21.0
118.5
94.0
0.0
0.0
14.0
0.0
4.0
5.0
10.5
59.0
167.0
0.0
1.0
1.0
12.0
13.0
98.5
9.0
141.0
3.0
1.0
22.0
3.0
4.0
30.0
13.5
19.0
23.0
38.0
4.0
7.0
349.5
1.0
31.5
58.0
0.0
0.0
10.0
21.5
5.0
0.5
72.0
18.5
25.5
20.0
83.0
11.5
7.5
5.5
5.5
1.0
8.0
102.5
0.0
25.0
1.0
11.0
19.0
43.5
3.0
30.0
0.0
9.5
0.5
13.5
8.0
10.0
0.0
316.0
6.0
17.5
53.0
7.0
9.0
38.0
58.5
12.0
31.5
47.0
28.0
0.0
11.0
33.0
4.0
14.0
86.0
0.0
0.0
3.5
17.5
12.0
357.0
29.0
86.5
37.5
0.0
80.5
3.0
23.5
0.0
0.5
67.5
19.5
27.0
16.0
26.5
0.0
26.0
28.0
2.5
0.0
9.0
4.0
16.5
154.5
12.5
5.5
20.0
63.0
14.0
0.0
44.5
13.5
1.5
6.0
13.5
34.5
4.0
0.0
12.5
6.0
12.0
0.0
2.0
15.5

414

In [14]:
#erasing all pixes outside big contour
big_contour= max(contours, key=cv2.contourArea)
mask = cv2.drawContours(np.zeros(edges.shape[:2], dtype=np.uint8), [big_contour], -1, 255, -1)
result=cv2.bitwise_and(edges, edges, mask=mask)
cv2.imshow('result', result)
cv2.waitKey(50000)
cv2.destroyAllWindows()

In [15]:
points=cv2.findNonZero(thresh)
rect=cv2.minAreaRect(points)#minimum area rotated rectangular box around contours
box=cv2.boxPoints(rect)#obtaining 4 cornerpoints of rotated rectangle as [p1,p2,p3,p4]
box=np.int0(box)
print(box)
print("cnt is: ", cnt)
cv2.drawContours(imge, [box], 0, (0,0,255),2) #3-> index of contour
cv2.imshow("rec", imge)
cv2.waitKey(50000)
cv2.destroyAllWindows()

/tmp/ipykernel_1975/1111166997.py:4: DeprecationWarning: `np.int0` is a deprecated alias for `np.intp`.  (Deprecated NumPy 1.24)
  box=np.int0(box)


[[  0   0]
 [639   0]
 [639 479]
 [  0 479]]
cnt is:  [[[132   0]]

 [[132   2]]

 [[134   4]]

 [[142   4]]

 [[143   3]]

 [[143   2]]

 [[144   1]]

 [[144   0]]

 [[144   1]]

 [[141   4]]

 [[135   4]]

 [[132   1]]]


In [12]:
cv2.imshow('edge_cpy', edge_cpy)
cv2.imshow('edges', edges)
cv2.waitKey(5000)
cv2.destroyAllWindows()


In [16]:
contours15, hierarchy = cv2.findContours(edges, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)

max_contour_area = 0
largest_contour_index = -1
for i, contour in enumerate(contours15):
    contour_area = cv2.contourArea(contour)
    if contour_area > max_contour_area:
        max_contour_area = contour_area
        largest_contour_index = i
        
# Draw a white filled polygon of the largest contour
mask = np.zeros(edges.shape, np.uint8)
cv2.drawContours(mask, [contours15[largest_contour_index]], 0, 255, -1)

# Erase all the contours15 outside the largest contour area
erased = cv2.bitwise_and(edges, mask)

# Display the resulting image
cv2.imshow('Edges with largest contour', erased)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [25]:

contours1, hierarchy = cv2.findContours(erased, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
print(len(contours1))
# Find the index of the largest contour based on area
max_contour_idx = max(range(len(contours1)), key=lambda i: cv2.contourArea(contours1[i]))

# Create a mask image of the same size as the original image
mask = np.zeros_like(erased)

# Draw the largest contour in white on the mask image
cv2.drawContours(mask, contours1, max_contour_idx, (255, 255, 255), cv2.LINE_AA)

# Invert the mask image
mask_inv = cv2.bitwise_not(mask)

# Apply the mask to the Canny image to remove the largest contour
edges_without_largest_contour = cv2.bitwise_and(erased, mask_inv)

# Display the result
cv2.imshow('Edges without largest contour', edges_without_largest_contour)
cv2.waitKey(0)
cv2.destroyAllWindows()


1


In [26]:
# Remove small contours
min_contour_area = 100  # set the minimum contour area threshold
for contour in contours:
    contour_area = cv2.contourArea(contour)
    if contour_area < min_contour_area:
        cv2.drawContours(edges_without_largest_contour, [contour], 0, 0, -1)

# Display the resulting image
cv2.imshow('Edges with small contours removed', edges_without_largest_contour)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [55]:

#removing small contours
_, thresh3=cv2.threshold(edges_without_largest_contour, 127, 255, cv2.THRESH_BINARY)
contours3, _= cv2.findContours(thresh3, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

# Loop through contours
for cnt in contours3:
    if cv2.contourArea(cnt)< 10 :
        cv2.drawContours(thresh3, [cnt], 0, 0, -1)
    

cv2.imshow('thresh3', thresh3)
cv2.imshow("remo_edges", edges_without_largest_contour)

cv2.waitKey(50000)
cv2.destroyAllWindows()

In [82]:
#puuting rectangle over object
points2=cv2.findNonZero(thresh3)
rect1=cv2.minAreaRect(points2)#minimum area rotated rectangular box around contours
box1=cv2.boxPoints(rect1)#obtaining 4 cornerpoints of rotated rectangle as [p1,p2,p3,p4]
box1=np.int0(box1)
print("box1 is: ",box1)
print("cnt is: ", cnt)
cv2.drawContours(imge, [box1], 0, (0,0,255),2) #3-> index of contour
cv2.imshow("rec", imge)
cv2.waitKey(50000)
cv2.destroyAllWindows()

/tmp/ipykernel_5183/449402079.py:5: DeprecationWarning: `np.int0` is a deprecated alias for `np.intp`.  (Deprecated NumPy 1.24)
  box1=np.int0(box1)


box1 is:  [[ 59 197]
 [ 77 182]
 [234 383]
 [216 397]]
cnt is:  [[[ 70 189]]

 [[ 70 190]]

 [[ 71 191]]

 [[ 71 193]]

 [[ 73 195]]

 [[ 73 197]]

 [[ 75 199]]

 [[ 75 200]]

 [[ 76 201]]

 [[ 76 202]]

 [[ 78 204]]

 [[ 78 206]]

 [[ 79 207]]

 [[ 79 208]]

 [[ 80 209]]

 [[ 80 210]]

 [[ 81 211]]

 [[ 81 212]]

 [[ 83 214]]

 [[ 83 215]]

 [[ 84 216]]

 [[ 84 217]]

 [[ 86 219]]

 [[ 86 220]]

 [[ 87 221]]

 [[ 87 222]]

 [[ 88 223]]

 [[ 88 224]]

 [[ 89 225]]

 [[ 89 226]]

 [[ 92 229]]

 [[ 92 230]]

 [[ 96 234]]

 [[ 96 235]]

 [[ 98 237]]

 [[ 98 238]]

 [[102 242]]

 [[102 243]]

 [[105 246]]

 [[105 247]]

 [[109 251]]

 [[109 252]]

 [[113 256]]

 [[113 257]]

 [[116 260]]

 [[116 261]]

 [[119 264]]

 [[119 265]]

 [[123 269]]

 [[123 270]]

 [[126 273]]

 [[126 274]]

 [[129 277]]

 [[129 278]]

 [[133 282]]

 [[133 283]]

 [[136 286]]

 [[136 287]]

 [[140 291]]

 [[140 292]]

 [[144 296]]

 [[144 297]]

 [[148 301]]

 [[148 302]]

 [[151 305]]

 [[151 306]]

 [[155 310]]

In [86]:
#find dimensions of pen rectangle
print(box1)
x1,y1=box1[0]
w1=box1[1][0]-x1
h1=box[3][1]-y1
print((x1,y1),(x1+w1,y1+h1))
print("width{w1} and height{h1}", w1, h1)

[[ 59 197]
 [ 77 182]
 [234 383]
 [216 397]]
(59, 197) (77, 402)
width{w1} and height{h1} 18 205


In [95]:
# Define the dimensions of the white paper in inches
paper_width_inch =  11.6929 #we use 90 degree flipped papper
paper_height_inch = 8.2677


#define the dimensions of papper in cm 
paper_width_cm =  29.7 #we use 90 degree flipped papper
paper_height_cm =  21 
papper_pixel_width=w
papper_pixel_height=h
# Calculate the maximum dimensions of the rectangle that fit on the paper
max_rectangle_width_cm = paper_width_cm
max_rectangle_height_cm = paper_height_cm

# Check if the rectangle fits within the maximum dimensions of the paper
print(papper_pixel_width, papper_pixel_height)

566 370


In [96]:
#Scaling rectangle width
#width of rect on papper in opencv=566
#height of rect on papper in opencv=370
#orientation is 566 x 370
"""or"""
#11.6535in x 8.2677in or 29.7cm x 21cm
#29.7cm=566,  1cm width = 19.06
a_cm_width=papper_pixel_width/paper_width_cm
#21cm=370, 1cm height = 17.62
a_cm_height=papper_pixel_height/paper_height_cm
print("width hight of papper in pixel: ", a_cm_width, a_cm_height)
#1 inch width = 566/11.6929=48.4
#1 inch height = 370/8.2677 = 44.8

# Define the dimensions of the rectangle in cm after convert
rectangle_width_cm = w1/a_cm_width
rectangle_height_cm = h1/a_cm_height

if rectangle_width_cm <= max_rectangle_width_cm and rectangle_height_cm <= max_rectangle_height_cm:
    print("The rectangle fits within the constraints of the white paper.")
else:
    print("The rectangle does not fit within the constraints of the white paper.")


width hight of papper in pixel:  19.05723905723906 17.61904761904762
The rectangle fits within the constraints of the white paper.


In [97]:
print("width", rectangle_width_cm)
print("height", rectangle_height_cm)

width 0.9445229681978797
height 11.635135135135135
